// Auto-generated by extract-catalog.js — do not edit manually.
// Re-run the script whenever catalog.xlsx changes.
const PRODUCTS = [
  {
    "partNo": "560000",
    "description": "Biberach",
    "matSizeA": 1260,
    "matSizeB": 6000,
    "thickness": 8,
    "weight": 9,
    "designType": "Timber designs",
    "image": "images/560000.png",
    "link3d": "https://sketchfab.com/3d-models/biberach-23db86d5ee80482ba0cf5773aa468fc0"
  },
  {
    "partNo": "569130",
    "description": "Palma",
    "matSizeA": "",
    "matSizeB": "",
    "thickness": "",
    "weight": "",
    "designType": "",
    "image": "images/569130.jpg",
    "link3d": ""
  },
  {
    "partNo": "564600",
    "description": "Riad",
    "matSizeA": "",
    "matSizeB": "",
    "thickness": "",
    "weight": "",
    "designType": "",
    "image": "images/564600.jpg",
    "link3d": ""
  },
  {
    "partNo": "569329",
    "description": "Lahr",
    "matSizeA": "",
    "matSizeB": "",
    "thickness": "",
    "weight": "",
    "designType": "",
    "image": "images/569329.jpg",
    "link3d": ""
  },
  {
    "partNo": "",
    "description": "",
    "matSizeA": "",
    "matSizeB": "",
    "thickness": "",
    "weight": "",
    "designType": "",
    "image": "",
    "link3d": ""
  }
];
