// Auto-generated by extract-catalog.js — do not edit manually.
// Re-run the script whenever catalog.xlsx changes.
const PRODUCTS = [
  {
    "partNo": "560000",
    "description": "Biberach",
    "matSizeA": 1260,
    "matSizeB": 6000,
    "thickness": 8,
    "weight": 9,
    "designType": "Timber designs",
    "image": "images/560000.png"
  }
];
