// Auto-generated by extract-catalog.js — do not edit manually.
// Re-run the script whenever catalog.xlsx changes.
const PRODUCTS = [
  {
    "partNo": "560000",
    "description": "Biberach",
    "matSizeA": 1260,
    "matSizeB": 6000,
    "thickness": 8,
    "weight": 9,
    "designType": "Timber designs",
    "image": "https://sketchfab.com/3d-models/biberach-23db86d5ee80482ba0cf5773aa468fc0"
  }
];
