/**
 * extract-catalog.js
 * Run once: node extract-catalog.js
 *
 * Reads your .xlsx file, extracts:
 *   1. All embedded images (col G) → saved to ./images/<PartNo>.jpg
 *   2. Product rows               → written to ./products.js
 *
 * Requirements:
 *   npm install xlsx adm-zip fs-extra
 */

const XLSX   = require("xlsx");
const AdmZip = require("adm-zip");
const fs     = require("fs-extra");
const path   = require("path");

// ─── CONFIG ────────────────────────────────────────────────────────────────
const EXCEL_FILE  = "./data/catalog.xlsx";   // ← change to your filename
const OUTPUT_DIR  = "./assets/E-cat/Product/NOE";
const PRODUCTS_JS = "./data/products.js";
// ───────────────────────────────────────────────────────────────────────────

async function run() {
  await fs.ensureDir(OUTPUT_DIR);

  // ── 1. Extract embedded images from the .xlsx zip ──────────────────────
  // .xlsx files are ZIP archives; images live in xl/media/
  const zip        = new AdmZip(EXCEL_FILE);
  const zipEntries = zip.getEntries();

  const mediaEntries = zipEntries
    .filter((e) => e.entryName.startsWith("xl/media/"))
    .sort((a, b) => a.entryName.localeCompare(b.entryName));

  console.log(`Found ${mediaEntries.length} embedded image(s).`);

  // ── 2. Parse rows to get Part Numbers (used to name image files) ────────
  const wb   = XLSX.readFile(EXCEL_FILE);
  const ws   = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(ws, { defval: "" });

  // The image order in xl/media matches row order in the sheet.
  const partNumbers = rows.map((r) =>
    String(r["Part No."] ?? r["Part No"] ?? "").trim()
  );

  // Save each image named by its Part No.
  mediaEntries.forEach((entry, i) => {
    const ext     = path.extname(entry.entryName) || ".jpg";
    const partNo  = partNumbers[i] || `img_${i}`;
    const outPath = path.join(OUTPUT_DIR, `${partNo}${ext}`);

    zip.extractEntryTo(entry, OUTPUT_DIR, false, true);

    // adm-zip uses original filename; rename to part number
    const extracted = path.join(OUTPUT_DIR, path.basename(entry.entryName));
    if (fs.existsSync(extracted)) fs.renameSync(extracted, outPath);
    console.log(`  Saved: ${outPath}`);
  });

  // ── 3. Build products array ─────────────────────────────────────────────
  const products = rows.map((r, i) => {
    const partNo = String(r["Part No."] ?? r["Part No"] ?? "").trim();

    // Image extension from the embedded file (col G)
    const ext = (mediaEntries[i]
      ? path.extname(mediaEntries[i].entryName)
      : ".jpg") || ".jpg";

    return {
      partNo,
      description : String(r["Description"] ?? "").trim(),
      matSizeA    : r["Mat size A approx, mm"]    ?? r["Mat size A"] ?? "",
      matSizeB    : r["Mat size B approx, mm"]    ?? r["Mat size B"] ?? "",
      thickness   : r["Mat thickness approx. mm"] ?? r["Mat thickness approx, mm"] ?? r["Thickness"] ?? "",
      weight      : r["Weight kg/m2"] ?? r["Weight"] ?? "",
      designType  : String(r["Design Type"] ?? "").trim(),
      image       : partNo ? `images/${partNo}${ext}` : "",  // col G — embedded product photo
      link3d      : String(r["3D Link"] ?? "").trim(),        // col H — Sketchfab URL
    };
  });

  // ── 4. Write products.js ────────────────────────────────────────────────
  const js = `// Auto-generated by extract-catalog.js — do not edit manually.
// Re-run the script whenever catalog.xlsx changes.
const PRODUCTS = ${JSON.stringify(products, null, 2)};
`;
  await fs.writeFile(PRODUCTS_JS, js, "utf8");
  console.log(`\nWrote ${products.length} products to ${PRODUCTS_JS}`);
  console.log("Done! Your file structure should look like:\n");
  console.log("  your-site/");
  console.log("  ├── index.html");
  console.log("  ├── products.js      (generated)");
  console.log("  └── images/");
  console.log("      ├── 560000.jpg");
  console.log("      └── ...");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});